project                  = "accelerator-dev-b6f2"
project_prefix           = "accelerator"
region                   = "us-east4"
environment              = "dev"
user_management_base_url = "https://api-dev.accelerator.dsgov.demo.nuvalence.io/um"
